# Ultralytics YOLO 馃殌, AGPL-3.0 license
"""
Ultralytics modules.

Example:
    Visualize a module with Netron.
    ```python
    from ultralytics.nn.modules import *
    import torch
    import os

    x = torch.ones(1, 128, 40, 40)
    m = Conv(128, 128)
    f = f"{m._get_name()}.onnx"
    torch.onnx.export(m, x, f)
    os.system(f"onnxslim {f} {f} && open {f}")  # pip install onnxslim
    ```
"""
from .gddneck import *
from .block import (
    C1,
    C2,
    C3,
    C3TR,
    CIB,
    DFL,
    ELAN1,
    PSA,
    SPP,
    SPPELAN,
    SPPF,
    AConv,
    ADown,
    Attention,
    BNContrastiveHead,
    Bottleneck,
    BottleneckCSP,
    C2f,
    C2fAttn,
    C2fCIB,
    C3Ghost,
    C3x,
    CBFuse,
    CBLinear,
    ContrastiveHead,
    GhostBottleneck,
    HGBlock,
    HGStem,
    ImagePoolingAttn,
    Proto,
    RepC3,
    RepNCSPELAN4,
    RepVGGDW,
    ResNetLayer,
    SCDown,
    SBA,
    EnhancedSBA,
    SBA_DySample,
    SPPF_LSKA,
    SPDConv,
    CSPOmniKernel,
    DySample,
    LAWDS,
    C2f_ESC,
    Bottleneck_ConvAttn,
    C2f_ConvAttn,
    FocusFeature,
    LSKNet,
    C2f_DySnakeConv,
    CSP_MutilScaleEdgeInformationSelect,
    C2f_ConvFormerCGLU,
    DGAF,
    C2f_Star,
    C2f_AINLite,
    C2f_AINLite_ECA,
    C2f_StarAlign,
    C2f_HKSM,
    SGRNeck,
    DSR_C2f,
    Spectra_SPPF,
    SpectraLite_SPPF,
    RDS_C2f,
    SpectraEdge_SPPF,
    RDEA_C2f,
)
from .conv import (
    CBAM,
    ChannelAttention,
    Concat,
    Conv,
    Conv2,
    ConvTranspose,
    DWConv,
    DWConvTranspose2d,
    Focus,
    GhostConv,
    LightConv,
    RepConv,
    SpatialAttention,
    ADRConv,
)
from .head import OBB, Classify, Detect, Pose, RTDETRDecoder, Segment, WorldDetect, v10Detect, Detect_DyHead, Detect_LSCD
from .starnet import starnet_s050, starnet_s100, starnet_s150, starnet_s1, starnet_s2, starnet_s3, starnet_s4
from .labf_neck import LABFNeck, DLABFNeck, DynamicTripleFusion, AARFNeck
from .transformer import (
    AIFI,
    MLP,
    DeformableTransformerDecoder,
    DeformableTransformerDecoderLayer,
    LayerNorm2d,
    MLPBlock,
    MSDeformAttn,
    TransformerBlock,
    TransformerEncoderLayer,
    TransformerLayer,
)
from .aifi_wrapper import AIFIWrapper
from .rdaf import DyAlignUp, R2SF, FCRB, RDAFNode

__all__ = (
    "Conv",
    "Conv2",
    "LightConv",
    "RepConv",
    "DWConv",
    "DWConvTranspose2d",
    "ConvTranspose",
    "Focus",
    "GhostConv",
    "ChannelAttention",
    "SpatialAttention",
    "CBAM",
    "Concat",
    "TransformerLayer",
    "TransformerBlock",
    "MLPBlock",
    "LayerNorm2d",
    "DFL",
    "HGBlock",
    "HGStem",
    "SPP",
    "SPPF",
    "C1",
    "C2",
    "C3",
    "C2f",
    "C2fAttn",
    "C3x",
    "C3TR",
    "C3Ghost",
    "GhostBottleneck",
    "Bottleneck",
    "BottleneckCSP",
    "Proto",
    "Detect",
    "Segment",
    "Pose",
    "Classify",
    "TransformerEncoderLayer",
    "RepC3",
    "RTDETRDecoder",
    "AIFI",
    "AIFIWrapper",
    "DeformableTransformerDecoder",
    "DeformableTransformerDecoderLayer",
    "MSDeformAttn",
    "MLP",
    "ResNetLayer",
    "OBB",
    "WorldDetect",
    "v10Detect",
    "ImagePoolingAttn",
    "ContrastiveHead",
    "BNContrastiveHead",
    "RepNCSPELAN4",
    "ADown",
    "SPPELAN",
    "CBFuse",
    "CBLinear",
    "AConv",
    "ELAN1",
    "RepVGGDW",
    "CIB",
    "C2fCIB",
    "Attention",
    "PSA",
    "SCDown",
    "SBA",
    "EnhancedSBA",
    "SBA_DySample",
    "ConservativeSBA",
    "SPPF_LSKA",
    "SPDConv",
    "CSPOmniKernel",
    "DySample",
    "LAWDS",
    "C2f_ESC",
    "Bottleneck_ConvAttn",
    "C2f_ConvAttn",
    "ADRConv",
    "FocusFeature",
    "LSKNet",
    "MFFM",
    "C2f_DySnakeConv",
    "Detect_DyHead",
    "CSP_MutilScaleEdgeInformationSelect",
    "C2f_PCLA",
    "C2f_ConvFormerCGLU",
    "DGAF",
    "C2f_Star",
    "C2f_VehicleLite",
    "C2f_AINLite",
    "C2f_AINLite_ECA",
    "C2f_StarAlign",
    "C2f_HKSM",
    "Detect_LSCD",
    "starnet_s050",
    "starnet_s100",
    "starnet_s150",
    "starnet_s1",
    "starnet_s2",
    "starnet_s3",
    "starnet_s4",
    "SGRNeck",
    "DyAlignUp",
    "R2SF",
    "FCRB",
    "RDAFNode",
    "LABFNeck",
    "DLABFNeck",
    "DynamicTripleFusion",
    "AARFNeck",
    "DSR_C2f",
    "Spectra_SPPF",
    "SpectraLite_SPPF",
    "RDS_C2f",
    "SpectraEdge_SPPF",
    "RDEA_C2f",
)


